### ISSUE TITLE
[Feat] Door command

### ISSUE THREAD

**Issue by xamionex** [darmuh/TerminalStuff#1]
Just a `door` or `dr` command that toggles the ship's doors, if you need any reference, [TerminalExtras](https://thunderstore.io/c/lethal-company/p/anormaltwig/TerminalExtras/) has it

**Comment by darmuh** [comment]
I'm looking to try to implement this soon 👍

**Comment by darmuh** [comment]
This will be in the next big patch. Doing some final testing/work on it and plan to have it out within the next couple days
