### ISSUE TITLE
Recently not working with FastSwitchPlayerViewInRadar

### ISSUE THREAD

**Issue by PinipigCrunch01** [darmuh/TerminalStuff#10]
Hi, your mod is amazing which gives a lot of advantages for a terminal guy. However recently, it does not work with FastSwitchPlayerViewInRadar (mod that uses arrow keys for switching to players) which is also a great addition for terminals. As a terminal guy, your mod is very useful, and with FastSwitchPlayerViewInRadar, your mod will be so much better. It will be a great help tho, if it's fixed.

Note: I do not really know how these codings of mods work. I approach this github, because there might be an easy fix?

Thanks a lot! and great work!

**Comment by darmuh** [comment]
this is being tracked in #8 so i'm going to close this one.

Thanks for the bug report!
