### ISSUE TITLE
Security doors desynch

### ISSUE THREAD

**Issue by Zuploader** [darmuh/TerminalStuff#12]
Found a new one, idk if it's because of your mod or because of terminal api, but when you are using view monitor the secure doors inside the facility are not working. either you don't see the color of the door updating to tell you if it's closed (in red), or sometimes it just don't do anything when you type the door code. Usually it works for the first minute then it stop working

**Comment by darmuh** [comment]
could you send me a profile code so I can try to recreate this? My mod shouldn't be touching door codes at all and I don't think terminalAPI does either

**Comment by Zuploader** [comment]
Sure here it is 018c7fc4-cafb-d20e-ec56-91831f97f7da
Feel free to tell me if you see any other errors because i can't seem to get a clean list since a week..

**Comment by Zuploader** [comment]
Actually it was this one, with ship lobby 018c7fc9-1d2a-9844-f26e-e0217e42d929

**Comment by darmuh** [comment]
haven't gotten around to trying that profile code but was able to verify door codes work with my dev profile that has the following mods enabled:

darmuh-darmuhsTerminalStuff (my dev version that isn't out)
FlipMods-FasterItemDropship
kRYstall9-FastSwitchPlayerViewInRadar
NotAtomicBomb-TerminalApi
NotAtomicBomb-Terminal_History
Rozebud-FOV_Adjust
sinai-dev-UnityExplorer (this is a dev plugin)
RickArg-Helmet_Cameras
tinyhoot-ShipLoot

video:

https://github.com/darmuh/TerminalStuff/assets/152580271/9757464f-352f-4cff-85af-dbeb7ae7d84f

**Comment by darmuh** [comment]
I'll look into the profile code you gave once I have the time but i'm inclined to believe it isn't my mod causing the issues.

**Comment by darmuh** [comment]
> Sure here it is 018c7fc4-cafb-d20e-ec56-91831f97f7da Feel free to tell me if you see any other errors because i can't seem to get a clean list since a week..

Yea that profile code was throwing loads of errors. I couldnt even get it to let me launch with two instances to check the door codes 🙃

**Comment by darmuh** [comment]
@Zuploader I'll leave this open for now, let me know if you run into any more issues with a new profile code and i'll give it a try

**Comment by darmuh** [comment]
I'm gonna close this for now, if you experience this issue again please feel free to open another issue with a log file from when the issue occured.
