### ISSUE TITLE
Switch command with specified player no longer works

### ISSUE THREAD

**Issue by Snooziepup** [darmuh/TerminalStuff#15]
Typing a player name after "switch" to switch to that specific player does not appear to function with the mod installed.

**Comment by Snooziepup** [comment]
To clarify, attempting to switch to a specific player will instead trigger the basic switch command.

**Comment by darmuh** [comment]
hmmmm, I could have sworn I fixed this in the latest patch.

So is it that when you type switch <playername> it still switches to the player but does not stay on the right cams view? Does it still show at least one of them (cams/map/minicams/minimap/overlay) or does it completely hide all of those views like it did in previous patches?

It'd help if you could provide a video of the issue so I could see what is happening

**Comment by Snooziepup** [comment]
I mean when you try to put a player name after "switch" it ignores it and just does what the regular switch command would do.

**Comment by Sp1rit** [comment]
Both problems exist. "switch playername" doesnt work, and all overlays are hidden when switching.

**Comment by darmuh** [comment]
Okay, that's definitely not good. I'll be looking into it when I have the time

**Comment by darmuh** [comment]
This should (hopefully) be fixed in the latest patch 2.2.0

I'll let you both confirm before closing this issue @Sp1rit @BreadieSB

**Comment by Snooziepup** [comment]
seems to work properly now

**Comment by darmuh** [comment]
> seems to work properly now

glad to hear! I'll give @Sp1rit another day and if I dont hear that there's any more issues i'll close this issue till next time 😆

**Comment by Sp1rit** [comment]
Switching players works like a charm thank you! I opened another Issue regarding the minicams closing when entering a wrong command to not keep this open with "unrelated" stuff.

**Comment by darmuh** [comment]
Thanks for the updates! I'll take a look at the other issue soon 👍
