### ISSUE TITLE
Minor Compatibility Issues with Advanced Company

### ISSUE THREAD

**Issue by darmuh** [darmuh/TerminalStuff#16]
Issue 1: (alwayson)

> 
> Advanced Company seems to leave the terminal screen on by default with no configuration to disable this.
> 
> This will interfere with the alwayson command in this mod slightly, as the alwayson command does change the behavior of some of my terminal commands based on whether it is enabled or disabled.
> 
> If you play with the Advanced Company mod and this mod I recommend using the alwayson command so that my commands recognize that the screen is always on.
> 

Issue 2: (help command)

> Advanced Company, like this mod, changes the help command to show the commands it has available.
> 
> Currently my help command will replace their output at first, then if you run the help command again you will see a messy list of both my help command output and the added information from AdvancedCompany.
> 
> Currently this shouldn't affect your overall experience in-game, it will just be kinda ugly to look at. I will be addressing this issue once I find time and hopefully find a method that adds both my help command information as well as AdvancedCompany's information.

If you are aware of any other Compatibility Issues this mod has with Advanced Company that have not been addressed above please post them here. Thanks!

**Comment by maxkalem** [comment]
The help command has kinda the same issue with Lategame_Upgrades v2.8.6.

**Comment by darmuh** [comment]
> The help command has kinda the same issue with Lategame_Upgrades v2.8.6.

thanks for the heads up! I'm going to try to think of a creative solution to this issue, as I do still  want to provide a reference to all available commands in some way.

**Comment by darmuh** [comment]
> Lategame_Upgrades v2.8.6

![image](https://github.com/darmuh/TerminalStuff/assets/152580271/2c5a2fd7-7fb0-4331-8b95-3988a3d63e12)

added this specifically for Lategame_Upgrades v2.8.6, feel free to let me know if you come across any other mods I should add similar compatibility for 👍

**Comment by darmuh** [comment]
Advanced Company solution was a bit complex but got it looking fairly nice as well:

![image](https://github.com/darmuh/TerminalStuff/assets/152580271/7ece0cca-a154-481c-9d67-38787d90185c)

**Comment by darmuh** [comment]
these changes should be expected in the next upcoming patch

**Comment by darmuh** [comment]
these should be fixed in 2.2.1
