### ISSUE TITLE
Latest version is no longer compatible with clients that don't have the mod

### ISSUE THREAD

**Issue by Fently** [darmuh/TerminalStuff#18]
Version 2.2.0 broke compatibility with other clients that do not have the mod. When trying to join a modded or unmodded lobby where the host does not have this mod, a message is returned say "An error occured". Log gives no other indication. 

I have tested version 2.1.1 and had no issues.

**Comment by darmuh** [comment]
Someone else had mentioned this in the Lethal Company Modding discord thread for this mod recently. I'll see if there's anything I can do to "toggle" networking in a future update to "fix" this issue. That said, I'm thinking I may need to fork this mod into multiple terminal mods to provide a truly clean "fix" and also just split up some of the logic (like the cams commands combined with alwayson for example could be it's own standalone mod im sure). Something like this will take me a fair amount of time though. 


In the meantime, i'd recommend either ensuring the host has this mod installed or utilizing the patch before networking was added (2.1.1). Also, outside of a few issues with the switch command 2.1.1 was stable so shouldn't be an issue staying on it.


Also, could you tell me what features of the mod you  normally use as a non-host client side user? I've always developed this mod with the intention that the host would be running it, so I'd like more info on how people utilize the mod in this way. 

For example, I dont think there should ever be a non-host client-side mod that can affect a lobby's credits, yet i'm sure you've been able to gamble, run vitals, etc. as a non-host client in past versions. There's a lot of room for griefing/trolling there that I've always wanted to avoid.

**Comment by Fently** [comment]
Hello, a fix would indeed be difficult considering all the code changes made in the recent version, but would of course be appreciated whenever you feel like doing it. (_but if you could still push the switch target fix to version 2.1.1, I would not complain_)

As a non-host user, I use the mod so I can view cams alongside the minimap within the console, as well as for quality of life features like opening/closing the ship door and using the teleporters with commands. I believe I have tried the "scan for biological" command for 15 credits before, but I was hosting the lobby with clients that did not have the mod installed. Whether or not I could use lobby credits as a non-host user I do not know.

As for grief/trolling issues, I get where you're coming from, preventing the use of certain features is a responsible idea, but I've always found such protections to be overly safe and redundant. Lobby players can still decide for themselves if they want a player with those features in their lobby or not, and will kick them if they don't. More importantly, using your mod to grief would be too much work for a troll anyway. They'll either just use the vanilla in-game terminal commands, or use their own client to do it. It's up to you to decide though, I just felt like adding some thought as someone who used to mod minecraft and the likes in the past. ; )

**Comment by darmuh** [comment]
Unfortunately it doesn't look like I can push a "fix" where you can just toggle networking. It's either in the mod or not lol

I mentioned this on the LC Modding discord but i'll be making a separate branch of this mod that is client side only in the future. I'll update here once that is posted.

**Comment by darmuh** [comment]
So over the last couple days I spoke with some others about how adding a networking element works with LC mods and it gave me an idea on how to make it toggleable. Feature works from my own limited testing so I've pushed it to the latest version 2.2.1.

give it a try and let me know how it goes!

**Comment by Fently** [comment]
It worked great! Thanks for your hard work 🫡
