### ISSUE TITLE
Disable FOV dependency?

### ISSUE THREAD

**Issue by jvresol** [darmuh/TerminalStuff#19]
Hi! Solid mod you've made here! My friends and I really love what you got going on here, only issue is with the FOV dependency. From what we understand, the reason why the FOV mod is listed as a dependency is that there is only the one command that adjusts the FOV value. That is only 1 command out of the 37 commands your mod adds, so it isn't necessarily essential for this mod to work. Would it be possible for you to remove it from the dependency in the manifest? 

The reason I ask is because two of our friends have this strange issue where their PCs crash when they have the FOV added to our current mod list.  And with their slow primitive internet (LOL), using a mod manager is the only way they can get access to our mods in a timely fashion. But with mod managers, it forces users to download every dependency listed, and there's no way to bypass it from what we know. 

Thank you for reading!

**Comment by darmuh** [comment]
Yeah odd enough you're not the first person to request this. I'll make it a soft dependency in the next update 👍

**Comment by darmuh** [comment]
also I had no idea there was 37 commands now 👀

**Comment by darmuh** [comment]
2.2.3 update removes hard dependency of Fov_Adjust 👍
