### ISSUE TITLE
[Error  : Unity Log] ArgumentNullException: String reference not set to an instance of a String. Parameter name: s

### ISSUE THREAD

**Issue by Zuploader** [darmuh/TerminalStuff#20]
Hey, after a bunch of testing i find out that your mod is causing some errors log, doesn't happen if terminalStuff is off, maybe you can check what's the issue. It only happen when loading a game btw.

I will add the full log, the error is near to the end of the txt

[Error  : Unity Log] ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
Stack trace:
System.Text.Encoding.GetBytes (System.String s) (at <787acc3c9a4c471ba7d971300105af24>:IL_0012)
Unity.Netcode.CustomMessagingManager.UnregisterNamedMessageHandler (System.String name) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0000)
Unity.Netcode.Components.NetworkTransform.OnNetworkDespawn () (at <8405014387374c19a6350f43289ea251>:IL_0025)
Unity.Netcode.NetworkBehaviour.InternalOnNetworkDespawn () (at <895801699cfc4b4ab52267f31e2a4998>:IL_000D)
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.NetworkBehaviour:InternalOnNetworkDespawn()
Unity.Netcode.NetworkObject:InvokeBehaviourNetworkDespawn()
Unity.Netcode.NetworkSpawnManager:OnDespawnObject(NetworkObject, Boolean)
Unity.Netcode.NetworkSpawnManager:DespawnObject(NetworkObject, Boolean)
Unity.Netcode.NetworkObject:Despawn(Boolean)
Unity.Netcode.DefaultSceneManagerHandler:MoveObjectsFromSceneToDontDestroyOnLoad(NetworkManager&, Scene)
Unity.Netcode.NetworkSceneManager:UnloadScene(Scene)
<unloadSceneForAllPlayers>d__254:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[LogOutput.log](https://github.com/darmuh/TerminalStuff/files/13929943/LogOutput.log)

**Comment by darmuh** [comment]
Odd, I would guess this has to do with the networking component.

I'll look into it as best I can, definitely need help reproducing it though.

Some things you might be able to answer/provide:

Does the error occur with the networking config off?
Did you ever leave a lobby and then go make another? Sometimes things carry over between lobbies that shouldn't (which is stuff I have to fix)
Does this error break anything that you've noticed? 
Do you have a copy of your config file for the mod that you can share?



Thanks for the report, I'll look into this and see whats up.

**Comment by Zuploader** [comment]
config is almost default,
i think its happening even you first boot the game and start a lobby, also everytime you leave and reload a save
doesn't seem to break the game, but need more testing on longer session and in multiplayer
i can also send the modlist
[darmuh.txt](https://github.com/darmuh/TerminalStuff/files/13932485/darmuh.txt)

**Comment by darmuh** [comment]
Thanks for the config! I'll look into it when I find time. I would also appreciate the modlist so I can try to replicate the issue myself

**Comment by Zuploader** [comment]
Sure it should be this one 018d0b9f-4033-eba5-a968-f2a0c93562bb
Also, could it be possible to integrate the time of the day on the monitor ? Would be nice so i could get rid of an other mod that does it (Terminal Clock). And if you could add a feature like STOCKoverview which let you see the equipement you have in ship (x2 flashlight, x1 shovel, x4 talkie etc), your mod would be the ultimate package

**Comment by darmuh** [comment]
> Sure it should be this one 018d0b9f-4033-eba5-a968-f2a0c93562bb Also, could it be possible to integrate the time of the day on the monitor ? Would be nice so i could get rid of an other mod that does it (Terminal Clock). And if you could add a feature like STOCKoverview which let you see the equipement you have in ship (x2 flashlight, x1 shovel, x4 talkie etc), your mod would be the ultimate package

can add the features you've requested to my list. there's still a lot planned for this mod I just need to find the time to work on it lol

**Comment by darmuh** [comment]
I've 100% narrowed this error down to my nethandler spawning logic. 

Reproducing the error by 
>Launching game w/mod & networking config option enabled
>Loading a random save
>Quit back to main menu
>Load another Save
>Error appears

I am going to add some more null checks for when the nethandler is spawned to try and catch this and prevent it 👍

**Comment by darmuh** [comment]
2.2.3 update should remove this error from showing. Let me know if you see any other issues i'll leave this open for a day or so just to double check
