### ISSUE TITLE
Logs error spam with Lategame Upgrades when terminal is open after reloading new save

### ISSUE THREAD

**Issue by anon-cfg** [darmuh/TerminalStuff#21]
>Make new r2modman profile
>Install darmuhsTerminalStuff 2.2.4
>Install Lategame Upgrades 3.1.0
>Launch game, create new save, open terminal
>Exit to menu, create new save, open terminal
>Logs fill with errors while terminal is open, stops when closed.

[Error  : Unity Log] NullReferenceException
Stack trace:
TerminalStuff.AllMyTerminalPatches+UpdatePatch.Postfix (Terminal& __instance) (at <ca55161eb51b429399fa2114115ca5b9>:IL_00D4)
(wrapper dynamic-method) Terminal.DMD<Terminal::Update>(Terminal)

r2modman profile code: 018d3901-876c-6252-e0b2-b496240bf5ff

Attached log file
[LogOutput.log](https://github.com/darmuh/TerminalStuff/files/14031360/LogOutput.log)

**Comment by darmuh** [comment]
seems to be a compatibility issue with the new terminalclock feature (error is referencing this [patch](https://github.com/darmuh/TerminalStuff/blob/ba32ea8017e1c00ea8f7a4e1a5675e2aa0b39bd5/DarmuhsTerminalCommands/MyTerminalPatcher.cs#L59))

Recommend disabling it via the below config option till I can narrow it down to something more specific and release a hotfix

![image](https://github.com/darmuh/TerminalStuff/assets/152580271/c70cbc1a-3bee-47e4-bdcc-64607ee982c6)

**Comment by darmuh** [comment]
specifically something LGU is doing is making my __instance reference null, so maybe i'll look into an alternative method of keeping the clock updated (I did feel icky about having an update patch anyway)

**Comment by darmuh** [comment]
Let me know if the issue persists with version 3.0.0

I've completely reworked the mod which should improve compatibility issues with various mods
