### ISSUE TITLE
Error when starting lobby

### ISSUE THREAD

**Issue by Zuploader** [darmuh/TerminalStuff#22]
Sometimes i get this error when starting a lobby, and when accessing the terminal, the "typing field" is like invisble, you cant see anything you are typing and get stuck on the welcome screen, but i tried Flash 1 and i heard the noise buying
Remember it does not happen always, i feel like its random, and often after deleting you Lethal folder in %appdata% (might be linked to to the screen where you have to type your favorite animal?), but it also happen on a save where i had already typed my favorite animal so idk

Modlist: 018d446f-3bb5-547c-c7b2-4827310fea14

[SEND TO DARMUH cant seeTerminalTyping.log](https://github.com/darmuh/TerminalStuff/files/14060991/SEND.TO.DARMUH.cant.seeTerminalTyping.log)

![darmuh error cant see type in terminal](https://github.com/darmuh/TerminalStuff/assets/152256234/7003414f-c441-407c-a2fa-f22fd232a974)

**Comment by Zuploader** [comment]
[Player.log](https://github.com/darmuh/TerminalStuff/files/14068368/Player.log)

(When interacting with the terminalf first time)
![darmuh error](https://github.com/darmuh/TerminalStuff/assets/152256234/2eaad4b2-db5c-49c8-85a7-3cda67908681)

(after leaving it then reusing it)
![darmuh](https://github.com/darmuh/TerminalStuff/assets/152256234/ce5f2646-457e-466c-b11f-a45b5935c2bd)

can't navigate after this

**Comment by darmuh** [comment]
Please let me know if this issue persists in version 3.0.0

I've finished a complete mod rework that should hopefully have improved compatibility with various mods
