### ISSUE TITLE
Every command going to the moon screen

### ISSUE THREAD

**Issue by merteger** [darmuh/TerminalStuff#24]
I have tried disabling several mods to try and see what is causing the issue but I at a loss. If anyone can help me find which mod is conflicting that would be great. 
Thanks

Code for the mods used:
018db8e2-0e4e-dc62-a8f5-07b80c69e70f

**Comment by sennnnnri** [comment]
Same but it only sends me to the "moons" page when I use "view monitor" command.

My code:
018dde0a-fc52-85ec-a76d-8dbb7384ab39

**Comment by darmuh** [comment]
I believe this issue was caused by Lethal Level Loader and have implemented a fix (via a complete mod rework) in version 3.0.0

Please let me know if you continue to experience issues with 3.0.0

**Comment by sennnnnri** [comment]
Everything works perfectly after your mod overhaul, thank you so much!
Also, the ASCII art on the main page is adorable, I really hope you'll keep it and not put an image there, it fits the aesthetic so well.

**Comment by darmuh** [comment]
> Everything works perfectly after your mod overhaul, thank you so much! Also, the ASCII art on the main page is adorable, I really hope you'll keep it and not put an image there, it fits the aesthetic so well.

glad everything is working! I'm glad you liked the ascii art as well! Definitely will keep it but want to still provide an option to replace it with an image at some point 😁
