### ISSUE TITLE
Seeing Through Crewmates' Eyes

### ISSUE THREAD

**Issue by NyxxieV** [darmuh/TerminalStuff#26]
Hi there! I just updated to version 3.0.0 yesterday and have encountered a new bug.

We're playing with TheMostLethalCompany modpack, version 7.6.0. TerminalStuff is the only mod we've updated from the base pack.

The reason we updated was because of the terminal always showing the Moons screen (Only intrusive when using command 'View Monitor').

The update solved the issue, but caused another where my I joined my friend's game and was seeing through his eyes. I could still control my character, but my PoV was shared with his (First person in his character model. I couldn't control camera movements, only he could). Logging out and back in solved this issue in the moment, but it plagued us all night.

Upon further investigation, I learned that when hitting the white button on the pilot monitor to switch views caused this. When it was set to my view, I was seeing properly through my own character. When I switched to his view (with the button) I would see through his eyes.

Going to the console monitor and typing 'View Monitor' and using 'Switch' commands did not cause this problem. And once I had interacted this way, I was able to use the pilot monitor buttons properly.

Later we tried leaving him in the ship, but no matter what method he tried if he switched view to himself I would see through his eyes.

I don't have any screenshots or videos of the problems (Laptop struggles recording) but I can work to reproduce the issues if you need!

Thanks for the awesome mod!

**Comment by darmuh** [comment]
Ah I think I might know what would be causing this issue. I'll try to get this fixed soon 👍

**Comment by darmuh** [comment]
in the meantime i'd recommend trying this mod with OpenBodyCams.
You can disbale the main bodycam and there will still be a terminal bodycam created from my mod

**Comment by darmuh** [comment]
@NyxxieV hopefully fixed this in the latest patch (3.0.2). Please update and let me know if it happens again 😁

**Comment by NyxxieV** [comment]
@darmuh Thanks for the replies and quick updates! Will update tomorrow (later tonight actually) and hopefully test it out!

As a side note, we did update to 3.0.1 and still experienced the bug, but less frequently. And we have not played for 2 days, so I haven't tested the OpenBodyCams fix yet.

**Comment by darmuh** [comment]
> @darmuh Thanks for the replies and quick updates! Will update tomorrow (later tonight actually) and hopefully test it out!
> 
> As a side note, we did update to 3.0.1 and still experienced the bug, but less frequently. And we have not played for 2 days, so I haven't tested the OpenBodyCams fix yet.

I'm going to mark this as resolved for now. If you experience this issue any further please lmk in another issue or (if you can?) reopen this one.
