### ISSUE TITLE
Terminal vitals and bioscan

### ISSUE THREAD

**Issue by Castyblank320** [darmuh/TerminalStuff#28]
the upgrades doesn't appear on the terminal store, it will be great to add that, and if you set the cost to 0 it will appear that charge you with 0 credits and you money balance, i just want it to look more clean by desactivating show that information when the cost is 0.

The bioscan upgrade isn't deactivatable by configs file.

**Comment by darmuh** [comment]
This is something I could work on in the future. As it is now, these commands are completely separate from the store and handled exclusively by my mod's code. I agree that integrating them into the store would be better from a user experience 👍 

As for bioscan upgrade not being deactivatable, this looks to be something missed during the rework. I will have to look further into this.

**Comment by darmuh** [comment]
version 3.0.4 should have added the ability to deactivate bioscan upgrade via config.

Sorry for missing that.

**Comment by darmuh** [comment]
Hello,

version 3.1.0 has integrated these purchasable upgrades into the vanilla store. Thanks for the suggestion and let me know if you have any other issues/ideas!
