### ISSUE TITLE
feat: teleport player by name

### ISSUE THREAD

**Issue by ZachHaber** [darmuh/TerminalStuff#30]
Could you make the teleport command allow for teleporting a player by their name? e.g. "tp ted" to teleport a player named ted? That way you can do quick rescues without having to switch to the player first!

**Comment by darmuh** [comment]
Hello,

Sorry for the long wait, I've just added this feature to the latest update (3.1.0).

I actually had this feature prepared much sooner but did not have the mod in a releasable state until now.

Anyway, try it and let me know what you think!
