### ISSUE TITLE
View monitor scale too small

### ISSUE THREAD

**Issue by LilacGiant** [darmuh/TerminalStuff#32]
Maybe to add an option to switch to default scale while at view monitor (maps)? Currently it's way smaller that default one and it's hard to see door and turret codes that are a bit far away from the player as well as to track enemies.

**Comment by darmuh** [comment]
I'll look into both a command for toggling this as well as a QoL feature for setting the default map scale 👍

**Comment by darmuh** [comment]
added this requested feature in version 3.3.0

 - Added radarZoom command to change the zoom level of the terminal radar.
	- Built-in compatibility with tworadarmaps
	- currently rotates through a range of possible zoom levels, each time you run the command.
	- may add further configurables to this in the future.
	- zoom levels will be synced with the rest of the lobby if networkedNodes is enabled.
		- Without tworadarmaps this WILL affect the mapscreen in the terminal.
 - Also added [TerminalRadarDefaultZoom] as a quality of life config setting to change the default radarzoom.
	- This will be synced at each client load-in if networkedNodes are enabled.
	- While the radarZoom command is recommended to be used alongside this feature, it is not required.
