### ISSUE TITLE
Cant input anything on terminal

### ISSUE THREAD

**Issue by EmilianoPerezz** [darmuh/TerminalStuff#33]
I have this mod in a modpack that i make and i recently update it (havent play in a while), with this mod enable i cant write anything on the terminal.

**Comment by darmuh** [comment]
Hi, I fixed a recent issue that was discovered with blank text submissions. 

Please try updating to v3.6.0 and if you still experience any issues please provide:

-  logs from the issue
-  profile code or list of mods you are using
-  steps to reproduce (if possible)

**Comment by darmuh** [comment]
if this issue is still occurring please feel free to re-open the issue or open a new one
