### ISSUE TITLE
Many commands not showing / working

### ISSUE THREAD

**Issue by FrogFlavouredWater** [darmuh/TerminalStuff#36]
i cannot use the bind commands, lobby commands. they do not show up in game and when run result in [There was no action supplied with the word.]

even when the config options are enabled for this, they stil do not appear

**Comment by darmuh** [comment]
Can you send a profile code with the issues you're experiencing?

**Comment by FrogFlavouredWater** [comment]
Ill send you my profile code, but even on a clean profile it didnt work.

Code: 01929c1d-b3cf-21d9-e297-68a9f498f694

**Comment by darmuh** [comment]
so the code you sent me had both of these config options disabled.

![image](https://github.com/user-attachments/assets/442bc8c0-424d-4dbc-acb6-d2645701f3e7)

After enabling them the following commands seem to work fine:
![image](https://github.com/user-attachments/assets/81e8fd7d-742d-4517-850d-1a4f473d0b70)
![image](https://github.com/user-attachments/assets/471a7c96-acb5-42c5-bc5b-1cc4b3d986d0)
![image](https://github.com/user-attachments/assets/32ad1dc5-0952-426b-bd94-205723b4904a)
![image](https://github.com/user-attachments/assets/fa01d97e-0c2b-4dda-bcbf-4919840a0c51)
![image](https://github.com/user-attachments/assets/c34d6913-03d8-49a3-b9d0-7d25533d7d68)

**Comment by darmuh** [comment]
also love the speaker music lmao

**Comment by FrogFlavouredWater** [comment]
Hi, thanks for the help. I'm very confused since i'm sure that I toggled them in setting.


Perhaps i'm going schizophrenic then. Oh well, can't have everything.

In all seriousness, i've realised I potentially didn't apply my Lethal Config settings 💀

**Comment by darmuh** [comment]
lol no worries, glad I could help figure it out 😁

**Comment by FrogFlavouredWater** [comment]
Hi, after spending an ungodly amount of time trying to fix this, i have found that all commands work other than the `bind` command.

Here is the output when I type bind: 
![image](https://github.com/user-attachments/assets/dfb1c6a6-928b-4ddf-be9f-db690e224441)

and here is the output when i type "bind f1 switch":
![image](https://github.com/user-attachments/assets/5fd2256a-11ed-4a0d-956e-73594126f61a)


I am using a completely clean profile with only these:
![image](https://github.com/user-attachments/assets/aa903c8e-a1db-4965-928c-e9cd483ba56f)

and the following entries are enabled:
![image](https://github.com/user-attachments/assets/f966427d-1766-47e7-8449-6844eae47a7e)
![image](https://github.com/user-attachments/assets/6d7eda51-31b8-437b-8323-d9ed75213702)

If you want, here is the code: 0192a063-cc6c-af3b-c22d-a152c19cc4f9
However it is literally completely fresh other than adding the mods you can see in the image a couple above
