### ISSUE TITLE
Commands confirmation

### ISSUE THREAD

**Issue by jacobmix** [darmuh/TerminalStuff#4]
There is already a mod that has command confirmation right now. Maybe see how they've done it:
https://thunderstore.io/c/lethal-company/p/Clementinise/QuickTerminalRestart/source/
Plus give credit, and all that.

**Comment by darmuh** [comment]
Thanks for the resource, will take a look at their code 👍

**Comment by darmuh** [comment]
Have this working now in my dev testing. Will probably get it out in the next patch update.

https://github.com/darmuh/TerminalStuff/assets/152580271/9059ac8d-b5f5-4c58-96ee-b6c49b25bad9
