### ISSUE TITLE
[Feat] Allow terminal text to be changed in config

### ISSUE THREAD

**Issue by jacobmix** [darmuh/TerminalStuff#5]
Allow terminal text to be changed in config would be nice like `NewTerminal` does.
Mainly add our own spins to some. Like gamble could mention a casino, streamer or some lore.
Tho probably keep the price to what it's actually set to. (NewTerminal doesn't have to worry about this. But i'm sure there's a way to do it)
Keeping all terminal text flexible will be good for people who want to be able to edit all terminal text, future commands too.
Btw maybe add `Help [Command]` text to all commands as well.

**Comment by darmuh** [comment]
hmmm I'll have to see about this later on down the line. I think I could allow config options for the verbiage commands use but it will be a bit time consuming. I also forgot to mention in the last readme that I do want to look into appending my own command list to the help command as well as other base terminal functionality. Since I'm using TerminalApi there's a chance Atomic may add this feature down the line as well.

**Comment by jacobmix** [comment]
Letting us change the command itself or add more ways to do the command would also be cool to config.
Like add "Launch", "Land" to "Leaver" or such. This is all harder to add i'm sure, and not expected to be implemented for now.
If this is something TerminalApi needs to add propper support for i can open an issue on their GitHub instead.

**Comment by darmuh** [comment]
Probably won't be able to change the keywords themselves, however, I am working on making the strings customizable for the next patch. Also working on some customizations for the gamble command specifically

This is how it'll look in the thunderstore config editor:
![image](https://github.com/darmuh/TerminalStuff/assets/152580271/09a84cc5-3dbc-4277-8242-afa27c3308f4)

**Comment by darmuh** [comment]
actually, I wont say changing the command keywords to be configurable is "impossible"

I can think of a few ways to maybe get that working but in those possible ways I think i'd need to restructure a good portion of my code. If there's enough demand for it I'll look into trying to implement it but for the time being i'd say that this specifically is a feature i'm not really going to pursue at the moment

**Comment by darmuh** [comment]
Actually wasnt as hard as I was making it out to be, just time consuming.

The config options even allow for a multiple word string to be your keyword such as "show map"

I will say that it is TEDIOUS to do these custom keywords so i'll probably limit it to one per command I've set it up for.

![image](https://github.com/darmuh/TerminalStuff/assets/152580271/0e097a77-0436-4707-b5f6-27770ea8d119)

**Comment by darmuh** [comment]
Last part of this thread I haven't added is a "help" command for info on other commands. I will work on this for future patches

**Comment by darmuh** [comment]
with OpenLib's latest automated info command creation I'm going to mark this issue resolved.

If anyone who reads this has any other ideas please open a new issue
