### ISSUE TITLE
[Feat] Custom Terminal adaptation

### ISSUE THREAD

**Issue by xamionex** [darmuh/TerminalStuff#6]
I read the issue before this one (#5) and was thinking of the same thing with [CustomTerminal](https://github.com/bzzzthe18th/customterminal)

If these 2 are added, this might be the best terminal mod ^^

**Comment by jacobmix** [comment]
Can't you just use CustomTerminal alongside this mod? Haven't tried that mod myself.

**Comment by xamionex** [comment]
Yeah but I have friends that for some reason think higher mods number = more unstable or too much when the half of the mods are qol

Up to the author tho

**Comment by darmuh** [comment]
I agree that you should (at least at the current moment) try running both mods together. If you run into compatibility issues feel free to let me know. 

As for my mod I had been thinking about adding some customizability to the terminal like the mod you linked but probably won't do anything like it any time soon. I'll make sure this gets added to the next readme as planned work. Thanks for the feedback I really appreciate it!
