### ISSUE TITLE
[Feat] Keep terminal on when exiting

### ISSUE THREAD

**Issue by xamionex** [darmuh/TerminalStuff#7]
Very useful when watching radar on terminal, I can't use CustomTerminal for this due to it overriding NewTerminal text :(

**Comment by darmuh** [comment]
I'll look into this

**Comment by Zuploader** [comment]
I would also really appreciate that

**Comment by darmuh** [comment]
have a prototype of this working in my dev branch

https://github.com/darmuh/TerminalStuff/assets/152580271/16bffdc3-9046-42b0-954e-9d44d3b17b08

**Comment by darmuh** [comment]
Feature has been added via the "alwayson" command in the latest patch (2.1.0)
